parsAndCutElf: convert line to str
Without this change, building with python3.x (python3.5 tested) as
/usr/bin/python will result in the following error:

Traceback (most recent call last):
  File "./parsAndCutElf.py", line 79, in <module>
    parserElf(sys.argv)
  File "./parsAndCutElf.py", line 54, in parserElf
    if( (line.find(firstSection) != -1) ):
TypeError: a bytes-like object is required, not 'str'

Change-Id: I0220d0457371349d0a77ac042484fd03f8a984da
Signed-off-by: Marty E. Plummer <hanetzer@startmail.com>
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/89385
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Reviewed-by: Srikantha S. Meesala <srikantha@in.ibm.com>
Reviewed-by: RAJA DAS <rajadas2@in.ibm.com>