buildInfo: Ensure we have a SBE_COMMIT_ID
It's currently possible to build the current sbe without having git
installed and have the compiler complain about:

sbecmdgeneric.C:54:18: error: unable to find numeric literal operator
‘operator""x’
     fwCommitId = SBE_COMMIT_ID;

This commmit makes it possible to specify a git SBE_COMMIT_ID, but fall back
to the old behavior of parsing the actual git data. It also makes sure
the process fails at this script instead of during compilation.

Signed-off-by: William A. Kennington III <wak@google.com>