buildInfo: Ensure we have a COMMIT_ID
It's currently possible to build the current sbe without having git
installed and have the compiler complain about:

sbecmdgeneric.C:54:18: error: unable to find numeric literal operator
‘operator""x’
     fwCommitId = SBE_COMMIT_ID;

This commmit makes it possible to specify a git COMMIT_ID, but fall back
to the old behavior of parsing the actual git data. It also makes sure
the process fails at this script instead of during compilation.

Signed-off-by: William A. Kennington III <wak@google.com>

Resolves #4

Resolves #4

Change-Id: I533d7914fe2f74a3540be87c6a5a2c2bb98ffc78
Reviewed-on: http://ralgit01.raleigh.ibm.com/gerrit1/39468
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Reviewed-by: Sachin Gupta <sgupta2m@in.ibm.com>